version: "3.8"

services:
  react-gap:
    container_name: react-gap
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ".:/var/www/"
      - "/var/www/node_nodules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
